local options= {
	{
		key="startmoney",
		name="Starting money",
		desc="the amount of money everyone starts with",
		type="number",
		def=500,
		min=100,
		max=3000,
		step=100,
		section="Money",
	},
	{
		key="planetcount",
		name="Number of planets for random patterns",
		desc="sets the number of planets for random patterns",
		type="number",
		def=10,
		min=2,
		max=20,
		step=2,
		section="Planet",
	},
	{
		key="pattern",
		name="Planet Pattern",
		desc="sets the pattern for the planets",
		type="list",
		def="randompoint",
		section="Planet",
		items = {
			{ key = "orion", name = "Orion", desc = "Safe outliers and a contested belt" },
			{ key = "standoff", name = "Standoff", desc = "Two opposing lines of planets" },
			{ key = "lineandside", name = "Line and Side", desc = "A central line and valuable caches off to the sides" },
			{ key = "trail", name = "Trail", desc = "A convenient trail from the northwest to the southeast" },
			{ key = "randompoint", name = "Random - Point Symmetry", desc = "Best for diagonals" },
			{ key = "randomx", name = "Random - East-West Symmetry", desc = "for east-west team games" },
			{ key = "randomz", name = "Random - North-South Symmetry", desc = "for north-south team games" },
			{ key = "random", name = "Random - No Symmetry", desc = "place all planets randomly" },
		}
	},
	{
		key="fastend",
		name="No planets = game over",
		desc="A team is eliminated when it goes one minute without holding a planet even if it has surviving ships.",
		type="bool",
		def="1",
		section="Rules",
	},
	{
		key="income",
		name="Income per planet",
		desc="Base income value for planets",
		type="number",
		def=10,
		min=1,
		max=100,
		step=1,
		section="Money",
	},
	{
		key="costmult",
		name="Cost multiplier",
		desc="Modifies cost of units (also multiplies starting money)",
		type="number",
		def=1,
		min=0.1,
		max=10,
		step=0.1,
		section="Money",
	},
	{
		key="perkcount",
		name="Number of perks",
		desc="Sets the number of perks each player is allowed to pick",
		type="number",
		def=3,
		min=0,
		max=12,
		step=1,
		section="Perks",
	},
	{
		key="burrowrespawn",
		name="Chicken Starbase Respawn",
		desc="Chicken/DotG starbases respawn when killed (not recommended for higher difficulties).",
		type="bool",
		def=false,
		section="Chicken",
	},
	{
		key="enableeclipse",
		name="Enable Eclipse",
		desc="Enables the Eclipse assault battlecruiser (may not be balanced)",
		type="bool",
		def=true,
		section="Experimental",
	},
	{
		key="changewaterlevel",
		name="Change water level",
		desc="Changes the water level (useful for sinking islands).",
		type="number",
		def=0,
		min=-5000,
		max=5000,
		step=1,
		section="Experimental",
	},
}

return options
