-- death_large
-- death_med_nospew
-- death_mega
-- death_med
-- death_huge
-- death_small
-- death_large_shock
-- death_multimed

return {
  ["death_large"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .8,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 40,
        particlelifespread = 20,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 2,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = .9,
        texture            = [[smoke1]],
      },
    },
    shock = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        damage             = 0,
        delay              = 24,
        dir                = [[0,1,0]],
        explosiongenerator = [[custom:death_large_shock]],
        pos                = [[0,0,0]],
        speed              = [[0,0,0]],
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 30,
        particlelife       = 60,
        particlelifespread = 20,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 3,
        particlespeedspread = 8,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_med_nospew"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .8,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 30,
        particlelifespread = 16,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 0,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = .9,
        texture            = [[smoke1]],
      },
    },
  },

  ["death_mega"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .93,
        alwaysvisible      = true,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 450,
        particlelife       = 50,
        particlelifespread = 32,
        particlesize       = 110,
        particlesizespread = 120,
        particlespeed      = 0,
        particlespeedspread = 140,
        pos                = [[0, 0, 0]],
        sizegrowth         = 14,
        sizemod            = .96,
        texture            = [[smoke1]],
      },
    },
    flash = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 0,
        colormap           = [[1 1 1 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 5,
        particlelife       = 16,
        particlelifespread = 8,
        particlesize       = 1500,
        particlesizespread = 400,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 1,
        sizemod            = 1,
        texture            = [[burncircle]],
      },
    },
    shockwave = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        alwaysvisible      = true,
        colormap           = [[1 1 1 .1   1 1 1 .1   0 0 0 0]],
        dir                = [[0, 1, 0.01]],
        frontoffset        = 0,
        fronttexture       = [[shockwave]],
        length             = 1,
        pos                = [[0, 0, 0]],
        sidetexture        = [[null]],
        size               = 1,
        sizegrowth         = 3800,
        ttl                = 120,
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        alwaysvisible      = true,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 300,
        particlelifespread = 160,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 6,
        particlespeedspread = 80,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_med"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .8,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 30,
        particlelifespread = 16,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 0,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = .9,
        texture            = [[smoke1]],
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 120,
        particlelifespread = 60,
        particlesize       = 3,
        particlesizespread = 2,
        particlespeed      = 3,
        particlespeedspread = 8,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_huge"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .93,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 150,
        particlelife       = 30,
        particlelifespread = 16,
        particlesize       = 40,
        particlesizespread = 10,
        particlespeed      = 0,
        particlespeedspread = 45,
        pos                = [[0, 0, 0]],
        sizegrowth         = 8,
        sizemod            = .96,
        texture            = [[smoke1]],
      },
    },
    shockwave = {
      air                = true,
      class              = [[CBitmapMuzzleFlame]],
      count              = 3,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        colormap           = [[1 1 1 .1   1 .8 .4 .1   0 0 0 0]],
        dir                = [[-.5 r1, 1, -.5 r1]],
        frontoffset        = 0,
        fronttexture       = [[shockwave]],
        length             = 1,
        pos                = [[0, 0, 0]],
        sidetexture        = [[null]],
        size               = 1,
        sizegrowth         = [[1100 i300]],
        ttl                = 60,
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 120,
        particlelifespread = 60,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 6,
        particlespeedspread = 20,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_small"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .8,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 12,
        particlelife       = 30,
        particlelifespread = 16,
        particlesize       = 20,
        particlesizespread = 10,
        particlespeed      = 0,
        particlespeedspread = 5,
        pos                = [[0, 0, 0]],
        sizegrowth         = 3,
        sizemod            = .9,
        texture            = [[smoke1]],
      },
    },
    shockwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 0,
        colormap           = [[1 .9 .5 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 12,
        particlelifespread = 4,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 12,
        sizemod            = 1,
        texture            = [[shockwave]],
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 10,
        particlelife       = 120,
        particlelifespread = 60,
        particlesize       = 1,
        particlesizespread = 1,
        particlespeed      = 3,
        particlespeedspread = 8,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_large_shock"] = {
    circle = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = .9,
        colormap           = [[1 .9 .4 .1   .8 .3 0 .1   0 0 0 1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 36,
        particlelife       = 10,
        particlelifespread = 66,
        particlesize       = 30,
        particlesizespread = 20,
        particlespeed      = 8,
        particlespeedspread = 10,
        pos                = [[0, 0, 0]],
        sizegrowth         = 4,
        sizemod            = .95,
        texture            = [[smoke1]],
      },
    },
    shockwave = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 0,
        colormap           = [[1 .9 .5 .1   0 0 0 0]],
        directional        = false,
        emitrot            = 0,
        emitrotspread      = 0,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 1,
        particlelife       = 12,
        particlelifespread = 4,
        particlesize       = 1,
        particlesizespread = 0,
        particlespeed      = 0,
        particlespeedspread = 0,
        pos                = [[0, 0, 0]],
        sizegrowth         = 12,
        sizemod            = 1,
        texture            = [[shockwave]],
      },
    },
    spew = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        airdrag            = 1,
        colormap           = [[1 .9 .1 .1   .5 .3 0 .1   0 0 0 0]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 140,
        emitvector         = [[0,1,0]],
        gravity            = [[0, 0, 0]],
        numparticles       = 90,
        particlelife       = 60,
        particlelifespread = 120,
        particlesize       = 6,
        particlesizespread = 2,
        particlespeed      = 1,
        particlespeedspread = 16,
        pos                = [[0, 1.0, 0]],
        sizegrowth         = 0,
        sizemod            = 1,
        texture            = [[puff]],
      },
    },
  },

  ["death_multimed"] = {
    explos = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 16,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        damage             = 0,
        delay              = [[r48]],
        dir                = [[0,1,0]],
        explosiongenerator = [[custom:death_med_nospew]],
        pos                = [[-50 r100,-50 r100,-50 r100]],
        speed              = [[0,0,0]],
      },
    },
    explos1 = {
      air                = true,
      class              = [[CExpGenSpawner]],
      count              = 6,
      ground             = true,
      water              = true,
      underwater    = true,
      properties = {
        damage             = 0,
        delay              = 0,
        dir                = [[0,1,0]],
        explosiongenerator = [[custom:death_med_nospew]],
        pos                = [[-30 r60,-30 r60,-30 r60]],
        speed              = [[0,0,0]],
      },
    },
  },

}

